// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAaNLDUvG498C6ngBm496HKjUx51AD0o',
    appId: '1:618160890478:web:4048b937374d0b79283c7f',
    messagingSenderId: '618160890478',
    projectId: 'act-7-9c86a',
    authDomain: 'act-7-9c86a.firebaseapp.com',
    storageBucket: 'act-7-9c86a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJTbzxg4U_-Ujrj166V1lIqT0ElHE5jw',
    appId: '1:618160890478:android:c04aaffcf8d2d5c9283c7f',
    messagingSenderId: '618160890478',
    projectId: 'act-7-9c86a',
    storageBucket: 'act-7-9c86a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeIQlTH8fqe9pxKzGJxZ7mQiV3YqANWqw',
    appId: '1:618160890478:ios:9484d07f9cd8b006283c7f',
    messagingSenderId: '618160890478',
    projectId: 'act-7-9c86a',
    storageBucket: 'act-7-9c86a.firebasestorage.app',
    iosBundleId: 'com.act-7.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeIQlTH8fqe9pxKzGJxZ7mQiV3YqANWqw',
    appId: '1:618160890478:ios:9484d07f9cd8b006283c7f',
    messagingSenderId: '618160890478',
    projectId: 'act-7-9c86a',
    storageBucket: 'act-7-9c86a.firebasestorage.app',
    iosBundleId: 'com.act-7.app',
  );
}
